// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CodexApp.Entities;

[Table("Attendance")]
public partial class Attendance
{
    [Key]
    public int AttendanceID { get; set; }

    public int? SessionID { get; set; }

    public int StudentID { get; set; }

    public bool IsAttended { get; set; }

    [ForeignKey("SessionID")]
    [InverseProperty("Attendances")]
    public virtual Session Session { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("Attendances")]
    public virtual Student Student { get; set; }
}