// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CodexApp.Entities;

public partial class Quiz
{
    [Key]
    public int QuizID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QuizName { get; set; }

    public int? EnrollmentID { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Grade { get; set; }

    public int? SessionID { get; set; }

    [ForeignKey("EnrollmentID")]
    [InverseProperty("Quizzes")]
    public virtual Enrollment Enrollment { get; set; }

    [ForeignKey("SessionID")]
    [InverseProperty("Quizzes")]
    public virtual Session Session { get; set; }
}