// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CodexApp.Entities;

public partial class Session
{
    [Key]
    public int SessionID { get; set; }

    [Required]
    [Unicode(false)]
    public string SessionName { get; set; }

    public int CourseID { get; set; }

    public int RoundNumber { get; set; }

    [Column(TypeName = "text")]
    public string MaterialLink { get; set; }

    [InverseProperty("Session")]
    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    [ForeignKey("CourseID, RoundNumber")]
    [InverseProperty("Sessions")]
    public virtual Course Course { get; set; }

    [InverseProperty("Session")]
    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    [InverseProperty("Session")]
    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    [InverseProperty("Session")]
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}