// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CodexApp.Entities;

public partial class Task
{
    [Key]
    public int TaskID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TaskName { get; set; }

    public int? EnrollmentID { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Grade { get; set; }

    public int? SessionID { get; set; }

    [ForeignKey("EnrollmentID")]
    [InverseProperty("Tasks")]
    public virtual Enrollment Enrollment { get; set; }

    [ForeignKey("SessionID")]
    [InverseProperty("Tasks")]
    public virtual Session Session { get; set; }
}